name: PR Tests
on: 
  workflow_dispatch:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: test
        run: | 
          sudo make install -C src/
          cd contrib/key-grid  && ./key-grid fill 10
          cat ./key-grid ls
          