name: PR Tests
on: 
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    types: [ assigned, opened, synchronize, reopened ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: test
        run: cd src && make && make install
